version: 0.2

phases:
  install:
    runtime-version:
      java: corretto8
  pre_build:
    commands:
      - aws s3 cp s3://sean-alfonso-api-p1/application.properties ./src/main/resources/application.properties
  build:
    commands:
      - echo Build started on 'date'
      - mvn package
      - mv target/*.war ./classmanager.war
  post_build:
    commands:
      - echo Build completed on 'date'
      - unzip classmanager.war -d artifact/
      - mv artifact/WEB-INF WEB-INF
artifacts:
  files:
    - WEB-INF/**/*
  name: artifact